version: '3.8'

services:
  mongo:
    image: "mongo:latest"
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: flux
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017

  indexer:
    build: .
    container_name: flux-indexer
    stop_signal: SIGTERM
    stop_grace_period: 200s
    environment:
      BITCOIN_NODE_URL: "http://127.0.0.1:8332"
      DATABASE_URL: "mongodb://username:password@mongo:27017/flux?authSource=admin"
    ports:
      - 3000:3000
    depends_on:
      mongo:
        condition: service_started
    volumes:
      - flux_indexer_container:/usr/src/app
    
volumes:
  flux_indexer_container:
  mongodb_data_container:
